[colors]
ansi = [
    "#2a2130",
    "#fd4663",
    "#c190df",
    "#d897d0",
    "#d49bb1",
    "#c7a1de",
    "#dca2d5",
    "#f2f2f3",
]
background = "#201a23"
brights = [
    "#6f6378",
    "#fd4663",
    "#c190df",
    "#d897d0",
    "#d49bb1",
    "#c7a1de",
    "#dca2d5",
    "#f2f2f3",
]
compose_cursor = "#f2f2f3"
cursor_bg = "#f2f2f3"
cursor_border = "#f2f2f3"
cursor_fg = "#201a23"
foreground = "#f2f2f3"
scrollbar_thumb = "#2a2130"
selection_bg = "#2a2130"
selection_fg = "#b3afb6"
split = "#6f6378"
visual_bell = "#2a2130"

[colors.indexed]
16 = "#d897d0"
17 = "#f2f2f3"

[colors.tab_bar]
background = "#201a23"
inactive_tab_edge = "#2a2130"

[colors.tab_bar.active_tab]
bg_color = "#c190df"
fg_color = "#1b171e"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#201a23"
fg_color = "#f2f2f3"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#201a23"
fg_color = "#f2f2f3"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#2a2130"
fg_color = "#f2f2f3"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#6f6378"
fg_color = "#f2f2f3"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[metadata]
author = "Noctalia"
name = "Noctalia"
